### PR TITLE
[PR] Switching `ImageButton` with custom button with same behaviour

### LINKED ISSUE #12: chore: Using `CustomButton` in place of `ImageButton`
For additional context, please see https://github.com/dwyl/app/pull/341#issuecomment-1747752793.

The `ImageButton` from `flutter_quill` has different behaviour when the app is accessed from a mobile app or a web browser. It uses [`kIsWeb`](https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html) to check if the platform is web-based or not - see https://github.com/singerdmx/flutter-quill/blob/8cb14b8155219a94c612467df79206ff09b9b386/flutter_quill_extensions/lib/embeds/toolbar/media_button.dart#L120.

Unfortunately, this makes it impossible to widget/integration/unit test web embeds and reduces the code coverage because there's no apparent way of overriding this variable during tests.

However, I believe we can work around this problem by having a [`CustomButton`](https://github.com/singerdmx/flutter-quill/blob/8cb14b8155219a94c612467df79206ff09b9b386/lib/src/widgets/toolbar/custom_button.dart#L6) that does the exact same thing an `ImageButton` does.

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #12 

⚠️ **Only merge after #11 is merged**.  ⚠️

This attempts to emulate `ImageButton`'s behaviour with a custom button that does this.
The reason we're doing this is described in #12.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
This is now ready for review.

**Only merge after #11 is merged**. 

Thanks 🙏

**Comment by nelsonic** [comment]
#11 merged. ✅

**Review by nelsonic — DISMISSED** [review]
@LuchoTurtle docs, tests & code look good. Thanks. 👌

**Review by nelsonic — DISMISSED** [review]
Merging. ✅

**Review by nelsonic — DISMISSED** [review]
Thanks @LuchoTurtle 👌

**Comment by nelsonic** [comment]
Merge Button is disabled for me ... 🤷‍♂️ 

image

**Review by nelsonic — APPROVED** [review]
Hopefully, final approval. 🤞

**Pull request merged**
